semester: Spring 2019
school: SF State
save_location: Z:\Edit Files\semesters\Spring 2019
iLearn_page: https://ilearn.support.at.sfsu.edu/ay1819/local/hub/extlogin.php?wantsurl=https%3A%2F%2Filearn.support.at.sfsu.edu%2Fay1819%2F
referrer_page: https://ilearn.support.at.sfsu.edu
iLearn_pass: 
iLearn_login:
base_ilearn_course_url: https://ilearn.support.at.sfsu.edu/ay1819/course/view.php?id=
ereserves_base_url: https://ilearn.support.at.sfsu.edu/blocks/ereserves/view.php
global_login_url: https://idp.sfsu.edu
global_login_username: 
global_login_password: 
