# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\913678186\Documents\ScraperGui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1401, 692)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(890, 20, 461, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.textEdit_courseid = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_courseid.setFont(font)
        self.textEdit_courseid.setObjectName("textEdit_courseid")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEdit_courseid)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.textEdit_savefolder = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_savefolder.setFont(font)
        self.textEdit_savefolder.setObjectName("textEdit_savefolder")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textEdit_savefolder)
        self.textEdit_semester = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_semester.setFont(font)
        self.textEdit_semester.setObjectName("textEdit_semester")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit_semester)
        self.pushButton_openconnection = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_openconnection.setGeometry(QtCore.QRect(50, 20, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_openconnection.setFont(font)
        self.pushButton_openconnection.setObjectName("pushButton_openconnection")
        self.pushButton_updateselected = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_updateselected.setGeometry(QtCore.QRect(50, 200, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_updateselected.setFont(font)
        self.pushButton_updateselected.setObjectName("pushButton_updateselected")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(360, 30, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(50, 90, 291, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_downloadamp = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_downloadamp.setFont(font)
        self.pushButton_downloadamp.setObjectName("pushButton_downloadamp")
        self.verticalLayout.addWidget(self.pushButton_downloadamp)
        self.pushButton_scancap = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_scancap.setFont(font)
        self.pushButton_scancap.setObjectName("pushButton_scancap")
        self.verticalLayout.addWidget(self.pushButton_scancap)
        self.widget1 = QtWidgets.QWidget(self.centralWidget)
        self.widget1.setGeometry(QtCore.QRect(890, 210, 461, 51))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_amptype = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_amptype.setFont(font)
        self.radioButton_amptype.setObjectName("radioButton_amptype")
        self.horizontalLayout.addWidget(self.radioButton_amptype)
        self.radioButton_cap_type = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_cap_type.setFont(font)
        self.radioButton_cap_type.setObjectName("radioButton_cap_type")
        self.horizontalLayout.addWidget(self.radioButton_cap_type)
        self.pushButton_addcourse = QtWidgets.QPushButton(self.widget1)
        self.pushButton_addcourse.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_addcourse.setFont(font)
        self.pushButton_addcourse.setObjectName("pushButton_addcourse")
        self.horizontalLayout.addWidget(self.pushButton_addcourse)
        self.widget2 = QtWidgets.QWidget(self.centralWidget)
        self.widget2.setGeometry(QtCore.QRect(50, 290, 1301, 351))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.listWidget_ampcourses = QtWidgets.QListWidget(self.widget2)
        self.listWidget_ampcourses.setObjectName("listWidget_ampcourses")
        self.verticalLayout_2.addWidget(self.listWidget_ampcourses)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.listWidget_capcourses = QtWidgets.QListWidget(self.widget2)
        self.listWidget_capcourses.setObjectName("listWidget_capcourses")
        self.verticalLayout_3.addWidget(self.listWidget_capcourses)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setCheckable(True)
        self.actionTest.setObjectName("actionTest")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Big Ham"))
        self.label_2.setText(_translate("MainWindow", "Course ID"))
        self.label_3.setText(_translate("MainWindow", "Semester"))
        self.label_4.setText(_translate("MainWindow", "Save Folder"))
        self.pushButton_openconnection.setText(_translate("MainWindow", "Open iLearn Connection"))
        self.pushButton_updateselected.setText(_translate("MainWindow", "Update Selected Course"))
        self.label_6.setText(_translate("MainWindow", "Session Label"))
        self.pushButton_downloadamp.setText(_translate("MainWindow", "Download AMP Courses"))
        self.pushButton_scancap.setText(_translate("MainWindow", "Scan Cap Courses"))
        self.radioButton_amptype.setText(_translate("MainWindow", "AMP"))
        self.radioButton_cap_type.setText(_translate("MainWindow", "Captioning"))
        self.pushButton_addcourse.setText(_translate("MainWindow", "Add Course"))
        self.label.setText(_translate("MainWindow", "Loaded AMP Courses"))
        self.label_5.setText(_translate("MainWindow", "Loaded CAP Courses"))
        self.actionTest.setText(_translate("MainWindow", "Test"))
        self.actionTest.setToolTip(_translate("MainWindow", "womppp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

